version: '2.0'

services:
  mongo:
    image: 'mongo:3.4.4'
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - 'mongo:/data/db'

  phaserquest:
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    image: 'chasey/chasey_game'
    command: node server.js -p 80 --mongoServer mongo --waitForDatabase 5000
    ports:
      - '80:80'


volumes:
  mongo:
